script: bundle exec rake test
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.1.0 # Problem with puppet monkey patch... waiting for >3.4.2
